// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToffeeTavern.Data;


#nullable disable

namespace ToffeeTavern.Migrations
{
    [DbContext(typeof(ToffeeContext))]
    partial class ToffeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToffeeTavern.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("C_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("C_LEVEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("C_NAME");

                    b.HasKey("Id");

                    b.ToTable("C_CHARACTER");
                });

            modelBuilder.Entity("ToffeeTavern.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Q_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("Q_C_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Q_DESCRIPTION");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Q_LOCATION");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Q_PRIORITY");

                    b.Property<string>("QuestGiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Q_QUEST_GIVER");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Q_STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Q_TITLE");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Q_TYPE");

                    b.HasKey("Id");

                    b.ToTable("Q_QUEST");
                });
#pragma warning restore 612, 618
        }
    }
}
